### ISSUE TITLE
Binaries link to 0.1 instead of 1.0 in (see inside)

### ISSUE THREAD

**Issue by Xanderplayz17** [TheRealMichaelWang/cish#36]
https://github.com/TheRealMichaelWang/superforth/wiki/Installation#running-pre-compiled-binaries

**Comment by TheRealMichaelWang** [comment]
This is a pretty serious bug. It will be resolved soon.

**Comment by Xanderplayz16** [comment]
I found out in README.md when you click Releases, it brings you to 0.1 too.

**Comment by Xanderplayz16** [comment]
Also I use Xanderplayz17 and this account, I do not want to explain why.

**Comment by TheRealMichaelWang** [comment]
Fixed in #40
