### ISSUE TITLE
Please explain

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#38]
In README.md, it says SuperForth can be both interpreted and compiled.
Well, where do I interpret it?

**Comment by TheRealMichaelWang** [comment]
The interpreter is located in [the current repository](https://github.com/TheRealMichaelWang/superforth).
The compiler is relatively new, and [is located here](https://github.com/TheRealMichaelWang/Capote)

Strictly speaking the only difference between the two is that the compiler lacks static linking with ffi c code.
