### ISSUE TITLE
Supposed to be cish, not superforth!

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#41]
![image](https://user-images.githubusercontent.com/74632800/175810049-1133198b-8984-4385-aa7f-fbe236884a8c.png)

**Comment by TheRealMichaelWang** [comment]
Yeah I need some help renaming. 

You need github enterprise/pro to be able to perform a batch replace, and I'm currently sorting out some issue with my account so I can get a student github account with my school email.

**Comment by Xanderplayz16** [comment]
Pretty sure I renamed all instances of Superforth to cish a while ago.

**Comment by TheRealMichaelWang** [comment]
Not sure what's going on then.
