### ISSUE TITLE
Does \a work like c?

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#42]

**Comment by TheRealMichaelWang** [comment]
uh as far as I'm aware there is no `\a` in Cish.

Here is the code for scanning characters, including special backslash characters:
```
#define RETURN(TYPE) { scanner->last_char = TYPE; break; }
int scanner_scan_char(scanner_t* scanner) {
	scanner_read_char(scanner);
	if (scanner->last_char == '\\') {
		scanner_read_char(scanner);
		switch (scanner->last_char)
		{
		case 'b':
			RETURN('\b');
		case 'e':
			RETURN('\e');
		case 'n':
			RETURN('\n');
		case 'r':
			RETURN('\r');
		case 't':
			RETURN('\t');
		case '\\':
			RETURN('\\');
		case '\"':
			RETURN('\"');
		case '0':
			RETURN(0);
		default:
			PANIC(scanner, ERROR_UNEXPECTED_TOK);
		}
	}
	return 1;
}
```
It doesn't have a `\a` I'm afraid, so **Cish doesn't support `\a**.

**Comment by TheRealMichaelWang** [comment]
[More C Escape Characters have been added](https://github.com/TheRealMichaelWang/cish/commit/48c1033006f30e2a14ea7c1d98d9fc9d1218c1b4) to Cish, including `\a`!

For reference, I've used [the following table](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) from wikipedia.

**Comment by 05st** [comment]
testing 123
