### ISSUE TITLE
Update FFI Table in wiki

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#47]

**Comment by TheRealMichaelWang** [comment]
The FFI documentation has been fully updated, you can [view the document here](https://github.com/TheRealMichaelWang/cish/wiki/Foreign-Function-Interface). 

Here are some links to the source for further information
- [The source for the interpreters implementation of the standard foreign functions](https://github.com/TheRealMichaelWang/cish/blob/main/src/stdlibf.c)
- [The source for the compilers runtime, and standard foreign function implementations](https://github.com/TheRealMichaelWang/Capote/blob/main/stdheader.c)
  - [PROS C Api, what `robomode` foreign functions are built off of](https://pros.cs.purdue.edu/v5/api/c/index.html)
