### ISSUE TITLE
Improve procedures wiki page

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#49]
Add how to define procedures and how to add inputs/outputs to them.

**Comment by TheRealMichaelWang** [comment]
There are multiple ways to define a procedure - see [this wiki page](https://github.com/TheRealMichaelWang/cish/wiki/Procedures) for more details.

Per the wiki page,
However there are other ways to declare a procedure that are often times less verbose:
- ### For regular, named functions
```
proc helloThere(array<char> msg) {
  println(msg);
}
```
The above is the equivalent to:
```
global readonly auto helloThere = proc(array<char> msg) return nothing {
  println(msg);
}
```
and if it's declared inside another function (or any non-global context), `helloThere` is translated to {
```
readonly auto helloThere = proc(array<char> msg) return nothing {
  println(msg);
}
```
- ### For "lambdas"
```
proc myLambda(int a, int b) => a + b;
```
or
```
sort(myNums, proc(int a, int b) => a - b); 
```
In addition, you actually don't have to specify a return type (ie `return nothing`, `return int`) so long as Cish can properly infer the type.
In addition you don't need curly brackets so long the procedure only has one statement - this also apply's to all conditionals as well, include `if`, `else`, `while`, and `for`.
