### ISSUE TITLE
Change the source file extension

### ISSUE THREAD

**Issue by ghost** [TheRealMichaelWang/cish#50]
The .csh extension is of the C Shell (https://en.wikipedia.org/wiki/C_shell).

**Comment by Xanderplayz16** [comment]
I would but I have no ideas for the file extension.
Do you have any?

**Comment by va0dl914** [comment]
> I would but I have no ideas for the file extension. Do you have any?

What about *.cish? :smile:

**Comment by Xanderplayz16** [comment]
That seems good, maybe that is what we will use!
