### ISSUE TITLE
Text editors support Cish?

### ISSUE THREAD

**Issue by 44iCdnz** [TheRealMichaelWang/cish#54]
At least syntax highlighting?

**Comment by TheRealMichaelWang** [comment]
I've been trying to work on a VS Code extension, albeit that effort has stalled.

**Comment by 44iCdnz** [comment]
@TheRealMichaelWang You liked closing issue when they are not yet resolved didn't you?

**Comment by 44iCdnz** [comment]
Someone asked for a lexer for Cish on CudaText repo. But now I think it's right for the CudaText developer to refuse it. With such an attitude, you should keep Cish for yourseft. I will not use it.

https://github.com/Alexey-T/CudaText/issues/4440
