### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by iahunq** [TheRealMichaelWang/cish#57]

**Comment by TheRealMichaelWang** [comment]
No, although there aren't any new features, this project is still being maintained. Any bug reports will be handled and fixed.

**Comment by iahunq** [comment]
> No, although there aren't any new features, this project is still being maintained. Any bug reports will be handled and fixed.

An issue as trivial as this is still not resolved: https://github.com/TheRealMichaelWang/cish/issues/48
